#!/usr/bin/env bash

# Shared defaults. Override any value before invoking a script, for example:
# NUM_PROCESSES=8 DEVICE=npu:0 bash scripts/train_colqwen2.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DATA_ROOT="${DATA_ROOT:-${PROJECT_ROOT}/data_dir}"
MODEL_ROOT="${MODEL_ROOT:-${PROJECT_ROOT}/models}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${PROJECT_ROOT}/outputs}"
HF_HOME="${HF_HOME:-${PROJECT_ROOT}/.cache/huggingface}"

TRAIN_DATASET="${TRAIN_DATASET:-${DATA_ROOT}/train}"
EVAL_DATASET="${EVAL_DATASET:-${DATA_ROOT}/eval}"
DEVICE="${DEVICE:-auto}"
NUM_PROCESSES="${NUM_PROCESSES:-1}"
PER_DEVICE_BATCH_SIZE="${PER_DEVICE_BATCH_SIZE:-1}"
TARGET_BATCH_SIZE="${TARGET_BATCH_SIZE:-128}"
EPOCHS="${EPOCHS:-1}"
LEARNING_RATE="${LEARNING_RATE:-5e-5}"
EVAL_SAMPLES="${EVAL_SAMPLES:-500}"
REPORT_TO="${REPORT_TO:-none}"
RUN_NAME="${RUN_NAME:-}"

export HF_HOME
mkdir -p "${DATA_ROOT}" "${MODEL_ROOT}" "${OUTPUT_ROOT}" "${HF_HOME}"

# Keep the effective batch close to TARGET_BATCH_SIZE on any device count.
DENOMINATOR=$((NUM_PROCESSES * PER_DEVICE_BATCH_SIZE))
GRADIENT_ACCUMULATION_STEPS=$(((TARGET_BATCH_SIZE + DENOMINATOR - 1) / DENOMINATOR))
export PROJECT_ROOT DATA_ROOT MODEL_ROOT OUTPUT_ROOT TRAIN_DATASET EVAL_DATASET
export DEVICE NUM_PROCESSES PER_DEVICE_BATCH_SIZE TARGET_BATCH_SIZE
export GRADIENT_ACCUMULATION_STEPS EPOCHS LEARNING_RATE
export EVAL_SAMPLES REPORT_TO RUN_NAME
